### ISSUE TITLE
no module named pyscopg2

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mac-packager#12]
Got "no module named pyscopg2" on startup - what am I missing?

**Comment by PeterPetrik** [comment]
Probably missing dependency of some of the installed plugins?

**Comment by PeterPetrik** [comment]
patch: https://github.com/lutraconsulting/qgis-mac-packager/commit/f0d3ec0fbe184861a53b8743650ce6a96a172dcd

**Comment by PeterPetrik** [comment]
fixed
