### ISSUE TITLE
Nightly builds requiring macOS 10.14

### ISSUE THREAD

**Issue by mapninja** [lutraconsulting/qgis-mac-packager#14]
The release page says Nightly Builds are supported on 10.11+, but both nightly builds I just tried prompted that 10.14 was required to run the app.

**Comment by saberraz** [comment]
@mapninja a PR is going to fix the issue in the main QGIS and the packages will be updated tomorrow.
https://github.com/qgis/QGIS/pull/8477

Meanwhile you can install this:
https://www.dropbox.com/s/jbkq4uw33wi05ud/qgis_nightly_master_20181113_104807.dmg?dl=0

**Comment by mapninja** [comment]
Rocking. Thanx!

**Comment by mapninja** [comment]
Just a heads up that the file you linked in the above comment has the same issue. Requires 10.14

**Comment by mapninja** [comment]
That's great. I have unsuccessfully installed it on 10.13.6. 
![screenshot 2018-11-13 12 36 44](https://user-images.githubusercontent.com/1517244/48441647-e4f53b00-e740-11e8-8428-c50133028011.png)

**Comment by saberraz** [comment]
Could you try and run it from terminal:
`cd /Applications/QGIS/QGIS.app/Contents/MacOS`
`./QGIS`

**Comment by mapninja** [comment]
That fired it up, with the usual plugin errors (should have nuked that folder before install). Here's the startup mesgs:

```
DN0a22c97c:MacOS maples$ ./QGIS
Warning: QWidget::insertAction: Attempt to insert null action
Warning: QWidget::insertAction: Attempt to insert null action
Warning: QWidget::insertAction: Attempt to insert null action
ERROR 4: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.
ERROR 4: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.
ERROR 4: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.
ERROR 4: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.
Warning: QLayout: Attempting to add QLayout "" to QmsSearchResultItemWidget "", which already has a layout
Warning: QLayout: Attempting to add QLayout "" to QmsSearchResultItemWidget "", which already has a layout
Warning: QLayout: Attempting to add QLayout "" to QmsSearchResultItemWidget "", which already has a layout
Warning: QLayout: Attempting to add QLayout "" to QmsSearchResultItemWidget "", which already has a layout
Warning: QLayout: Attempting to add QLayout "" to QmsSearchResultItemWidget "", which already has a layout
ERROR 4: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.```

**Comment by saberraz** [comment]
It is due to the python path which is picking 2.7 from the system and not the bundled frameworks.
