### ISSUE TITLE
Nightly Build, no processing tools

### ISSUE THREAD

**Issue by mapninja** [lutraconsulting/qgis-mac-packager#15]
Installed from Nightly Build. Was able to circumvent [#14](https://github.com/lutraconsulting/qgis-mac-packager/issues/14) by launching from terminal, but I get no processing tools. No processing menu, panel, etc...

macOS 10.13.6 and this nightly:
https://www.dropbox.com/s/jbkq4uw33wi05ud/qgis_nightly_master_20181113_104807.dmg?dl=0

**Comment by mapninja** [comment]
I did a clean install, purged the "~/Library/Application\ Support/QGIS/QGIS3" folder and still no good. 

I tried prepending the PATH to the bundled Python 3.7, but no luck:
"/Applications/QGIS.app/Contents/Frameworks/Python.framework/Versions/3.7/bin:"

**Comment by saberraz** [comment]
This is related to a missing dependency for the Processing Plugin #17

**Comment by PeterPetrik** [comment]
@saberraz @mapninja  can you please test with https://www.dropbox.com/s/69f3u5ow9pa8whz/qgis_nightly_master_20181114_084148.dmg?dl=0

**Comment by saberraz** [comment]
@PeterPetrik it is working for me now but with some workarounds to bypass #19

**Comment by JesusLopTem** [comment]
No processing tools also in El Capitan 10.11.6 with this late nightly

**Comment by PeterPetrik** [comment]
> No processing tools also in El Capitan 10.11.6 with this late nightly

@JesusLopTem 
any missing python packages reported in the python log console/console?

**Comment by JesusLopTem** [comment]
oops, no python console in menu

**Comment by saberraz** [comment]
I can confirm that there is also no Python support for Sierra (10.12)

**Comment by saberraz** [comment]
I am closing this and opening a new ticket.
