### ISSUE TITLE
PYTHONHOME is not set

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mac-packager#19]
When I try to run QGIS from terminal (not possible to run from Application due to #14), it comes up with:
`Consider setting $PYTHONHOME to <prefix> `
`ModuleNotFoundError: No module named 'encoding' `

Mac OS: 10.13

![image](https://user-images.githubusercontent.com/2649047/48467785-dca10c80-e7e1-11e8-9856-30bd39af8ab2.png)

**Comment by saberraz** [comment]
If I set the PYTHONHOME to /Applications/QGIS.app/Contents/Frameworks/Python.framework/Versions/Current it will work

For those with similar problem: in terminal:
`export PYTHONHOME=/Applications/QGIS.app/Contents/Frameworks/Python.framework/Versions/Current`

**Comment by PeterPetrik** [comment]
https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/LaunchServicesKeys.html#//apple_ref/doc/uid/20001431-106825

**Comment by saberraz** [comment]
For 10.13 and 10.14 it works fine. For 10.11 and 10.12 it is duplicate of #22
