### ISSUE TITLE
add netcdf support

### ISSUE THREAD

**Issue by PeterPetrik** [lutraconsulting/qgis-mac-packager#20]
https://github.com/OSGeo/homebrew-osgeo4mac/issues/521

**Comment by PeterPetrik** [comment]
If I build gdal2 with --with-complete it has netcdf4 support but on some computers it triggers https://github.com/lutraconsulting/qgis-mac-packager/issues/25  Crash is due to initialization of GDAL static variable in wms/minidriver.cpp . 
Bottled GDAL2 from osge4mac does not have netcdf, but does not crash anywhere.

One explanation could be that bottled gdal is compiled on earlier macOS, other one that it uses different compiler (clang vs gcc) or that hdf4 somehow corrupts the static variable

**Comment by PeterPetrik** [comment]
https://docs.brew.sh/Bottles


> By default, bottles will be built for the oldest CPU supported by the OS/architecture you’re building for (Core 2 for 64-bit OSs). This ensures that bottles are compatible with all computers you might distribute them to. If you really want your bottles to be optimized for something else, you can pass the --bottle-arch= option to build for another architecture; for example, brew install foo --build-bottle --bottle-arch=penryn. Just remember that if you build for a newer architecture some of your users might get binaries they can’t run and that would be sad!

**Comment by saberraz** [comment]
Now works in:
https://www.dropbox.com/sh/cc3615b1zd7ruwz/AABVWxRW3sLBXpEbAx8Di18xa/qgis_nightly_master_20181120_111516.dmg?dl=0

Try on other platforms and hopefully we can close this.
