### ISSUE TITLE
Missing dateutil module for Python

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mac-packager#21]
Mac OS 10.13

**Comment by PeterPetrik** [comment]
@saberraz can you try with this one please? https://www.dropbox.com/s/oq3cq9ttewp3uck/qgis_nightly_master_20181114_145615.dmg?dl=0

**Comment by saberraz** [comment]
Still it complains about the same missing module.

**Comment by PeterPetrik** [comment]
working for https://www.dropbox.com/s/wabszoic6rx397k/qgis_nightly_master_20181116_012525.dmg?dl=0
