### ISSUE TITLE
Python 3.7 references unavailable symbol _futimens on 10.11 and 10.12

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mac-packager#22]
There is no Python support for El Capitan and Sierra.

**Comment by PeterPetrik** [comment]
this is upstream bug in python3.x see https://bugs.python.org/issue31601

**Comment by PeterPetrik** [comment]
maybe use python from https://www.python.org/downloads/

**Comment by PeterPetrik** [comment]
This issue require considerable time to fix and funds were not raised in the crowdfunding in Feb 2019. It is put on hold until we got a sponsor for it or working PR to review.
