### ISSUE TITLE
Add SAGA support for some platforms

### ISSUE THREAD

**Issue by PeterPetrik** [lutraconsulting/qgis-mac-packager#32]
relates to https://github.com/lutraconsulting/qgis-mac-packager/issues/20

running saga_cmd on some platforms triggers "Illegal instruction 4" similar to gdal2 build.

**Comment by saberraz** [comment]
works in https://www.dropbox.com/sh/cc3615b1zd7ruwz/AABVWxRW3sLBXpEbAx8Di18xa/qgis_nightly_master_20181120_111516.dmg?dl=0

**Comment by saberraz** [comment]
It is not working for 10.11 and 10.12 because of #22 
Closing this but feel free to open if Python is resolved and still this is an issue.
