### ISSUE TITLE
Use different names for LTR, PR and NIGHTLY releases

### ISSUE THREAD

**Issue by Spartacus1** [lutraconsulting/qgis-mac-packager#37]
Just to say that this compilation is probably the best available for now. Working very good. 
I just want to ask if the name of the app can be QGIS3.app instead of QGIS.app. This will allow users to use the previous LTR at the same time. by using QGIS.app, the previous version will be replaced. 
Thank you for all your effort.

**Comment by PeterPetrik** [comment]
Hi, thanks! 

related to https://github.com/lutraconsulting/qgis-mac-packager/issues/11

**Comment by PeterPetrik** [comment]
Renamed (https://github.com/lutraconsulting/qgis-mac-packager/commit/d939212b9ac86153989907919faace4aaa3d2b07)

please check 
PR: QGIS3.4.2.app https://www.dropbox.com/s/dm0crl1y33783df/qgis_pr_final-3_4_2_20181130_083659.dmg?dl=0
NIGHTLY: QGIS3.5.app will come later today

**Comment by Spartacus1** [comment]
Outstanding Peter! Thank you for your nice effort. 
This version it’s working perfectly. 
You were quick to change the name of the app!
I’ll be testing the 3.5NB. 
Best Regards


-- 
Renato Henriques
Department of Earth Sciences
Campus de Gualtar
University of Minho
4710-057, Braga - Portugal
Tel +351 253604031
rhenriques@dct.uminho.pt
www.uminho.pt
