### ISSUE TITLE
Detached panels missing on hide

### ISSUE THREAD

**Issue by JesusLopTem** [lutraconsulting/qgis-mac-packager#39]
If you open one or more detached panels (processing tools, layers style or any other), all of them disappear when you hide Qgis and have to reopen them from menu.

Qgis 3.4.2 on 10.11.6 and 10.14.1

**Comment by saberraz** [comment]
In my case, they do not minimize with QGIS application and stay open. Not sure if this is an upstream bug or related to this package.

**Comment by PeterPetrik** [comment]
@JesusLopTem how it should behave (or what is standard for MacOS)? Are we sure this is not system-wide settings how to handle dispatched dialogs?

**Comment by JesusLopTem** [comment]
Hi @PeterPetrik. The standard in MacOS is maintain open windows when you hide an application and return to it, all applications, but Qgis, have this behavior. Qgis do, at least until version 3.2.0 but not in newer versions.

**Comment by JesusLopTem** [comment]
Anyone can confirm? Latest nightly version (qgis_nightly_master_20190217_121012) seems to solve the problem on 10.13.6

**Comment by PeterPetrik** [comment]
I did not change anything that I know of for this fix. Maybe there is something on the OS (there was system update recently)

**Comment by PeterPetrik** [comment]
@saberraz

**Comment by PeterPetrik** [comment]
The repository is no longer used, because QGIS Mac packaging system is moved under OSGEO/QGIS repository https://github.com/qgis/QGIS-Mac-Packager. Please reopen the issue in the new repository if it is still an issue
