### ISSUE TITLE
Background color can not be changed in Canvas & Legend settings

### ISSUE THREAD

**Issue by soli004** [lutraconsulting/qgis-mac-packager#40]
**Describe the bug**

Using latest version of QGIS version 3.4 and also tried latest dev of 3.5 on OSX 10.14.1
Issues is that you are not able to change the background from the default white to any other color. If trying to change you do get an Python error that does not seems to be related to the issue...
"RuntimeError: wrapped C/C++ object of type ShortestPathBetweenPoints has been deleted"

No crash and no change in color for the background but in the settings it has changed to the color you wanted.... restart QGIS does not help....

**Additional information**

- Add link to the installed package

https://lutraconsulting.github.io/qgis-mac-packager/

- Add crash report if QGIS crashed

Error message:
An error has occurred while executing Python code: 

RuntimeError: wrapped C/C++ object of type ShortestPathBetweenPoints has been deleted 
Traceback (most recent call last):
  File "/Users/name/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/QNEAT3/Qneat3Provider.py", line 106, in loadAlgorithms
    self.addAlgorithm(alg)
RuntimeError: wrapped C/C++ object of type ShortestPathBetweenPoints has been deleted

Python version: 3.7.1 (default, Nov  6 2018, 18:46:03) [Clang 10.0.0 (clang-1000.11.45.5)] 
QGIS version: 3.5.0-Master Master, 0af1ce40a8 
- State MacOS version (e.g. 10.14.1)

10.14.1
- The installation location of QGIS (must be /Applications/QGIS<suffix>.app)

/Applications/QGIS

**Comment by Spartacus1** [comment]
Try menu Project->Properties->General and then changed the Background color of the project. No problems here. The problem do occur when you try to change the background for any project from the general Preferences. In this case there will occur a crash and the plugin that is named in the "RuntimeError: wrapped C/C++ ..." usually varies. In my case is the ContourPlugin but it can be other. This is a common error in every version or compilation of QGIS3 in MacOS that I had used so far. The only way to avoid this for now is to do as I told in the beginning of this message which means that you have to be patient and change the background color for each project if desired.

**Comment by soli004** [comment]
Thank you, yes that did work...

**Comment by saberraz** [comment]
I suggest to open a ticket on QGIS:
https://issues.qgis.org/projects/qgis/issues
