### ISSUE TITLE
How to install python packages

### ISSUE THREAD

**Issue by AsgerPetersen** [lutraconsulting/qgis-mac-packager#41]
Is there a way to install further python packages in this build?

I have tried using pip from the QGIS python console like:
```
import pip
pip._internal.main(['install', 'kvadratnet'])
Collecting kvadratnet
  Downloading https://files.pythonhosted.org/packages/c0/54/678d3124a81c3792d820122e937d3b444de25940535b75697918aa59c2d5/kvadratnet-0.3.0-py2.py3-none-any.whl
Installing collected packages: kvadratnet
  The script knet is installed in '/usr/local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed kvadratnet-0.3.0
```

But the installed module cannot be `import`ed even after a restart of QGIS.

**Comment by PeterPetrik** [comment]
@AsgerPetersen thanks for reporting the issue. Does this approach work when using other MacOS QGIS packages? Also I want to ask if you tried to close QGIS, and `/usr/local/bin` to PATH as suggested and start QGIS again?

the install location seems to be the homebrew's default one, maybe related. to https://github.com/lutraconsulting/qgis-mac-packager/issues/31

**Comment by PeterPetrik** [comment]
Definitely the install path is wrong. But my point is that where it should be, or where it is for other distributions/OS/packages? I think somewhere in user's QGIS folder?

**Comment by AsgerPetersen** [comment]
Ah.

I think packages are tightly connected to the interpreter. So I am not sure installing in user's QGIS folder is a good idea.

Packages installed with the app are installed in `/Applications/QGIS3.4.2.app/Contents/Resources/python/`. If it is possible to write to that folder it would probably be a good place to put it.

Looking at the [pip documentation](https://pip.pypa.io/en/stable/user_guide/#using-pip-from-your-program) it is clear that we are not supposed to use pip the way I did above:
> While it is implemented in Python, and so is available from your Python code via import pip, you must not use pip’s internal APIs in this way. 

Instead they suggest doing it like
```python
import subprocess
import sys
subprocess.check_call([sys.executable, '-m', 'pip', 'install', 'my_package'])
```
But their suggested way of doing things does not work in this case as our `sys.executable` seems to be the qgis executable and I see no way to invoke it where it acts like the ordinary python interpreter.

It seems to be rather complicated to install further packages :-(

**Comment by PeterPetrik** [comment]
@AsgerPetersen are there any packages you need to have bundled and are not present ATM in the bundle? I tried to bundle all packages that are in OSGeo4W.

If you need an extra package in the QGIS plugin, what we usually do it to get a wheel from distribution and bundle in your plugin. See for example 
https://github.com/lutraconsulting/qgis-crayfish-plugin/blob/master/crayfish/gui/plot_widget.py#L37-L45

If you need global install (e.g. for QGIS Python console), just copy downloaded wheel to `/Applications/QGIS<version>.app/Contents/Resources/python/`, it should not break validation

**Comment by AsgerPetersen** [comment]
I think having the same packages as in OSGeo4W is going to cover most use cases.

Thank you!

**Comment by PeterPetrik** [comment]
Feel free to ping me on peter.petrik@lutraconsulting.co.uk if you need to discuss some additional packages to add. Closing this for now.

**Comment by PeterPetrik** [comment]
https://gist.github.com/AsgerPetersen/9ea79ae4139f4977c31dd6ede2297f90#python-dependencies
