### ISSUE TITLE
Saving dialog

### ISSUE THREAD

**Issue by Spartacus1** [lutraconsulting/qgis-mac-packager#42]
All the QGIS3.5 latest betas always ask for saving a project after opening when we still are in the recent projects list. 

MacOS version (e.g. 10.14.2)

**Comment by PeterPetrik** [comment]
@Spartacus1 can you please do screencast and append here? not sure if I understand it

**Comment by Spartacus1** [comment]
Hi Peter

I’m out for fieldwork for a few hours. Tonight I’ll send a video. 
Best Regards

No dia 05/12/2018, às 10:06, Peter Petrik <notifications@github.com> escreveu:

**Comment by saberraz** [comment]
I can't replicate your issue. It could be related to your profile. Worth starting with a fresh profile and see if you can reproduce the issue.

Also, I think it might be related to the QGIS and not packaging.

**Comment by Spartacus1** [comment]
See the error from the following video. A save dialogue appears from nothing and it's impossible to close the "Credits" window without press "Don't save". Version 3.4.2 it is rock stable. 

https://www.dropbox.com/s/a39wv03sqk2amg7/QGIS8_5_OPEN_ERROR.mp4?dl=0

**Comment by PeterPetrik** [comment]
This could be upstream issue.

**Comment by Spartacus1** [comment]
Probably Peter. However do not worry too much. This is not a bug that can disrupt any workflow. Probably it will be solved by itself. The only thing strange is that QGIS3.4 does not suffer from this issue.

**Comment by saberraz** [comment]
I have opened this ticket on QGIS bug tracker:
https://issues.qgis.org/issues/20741
