### ISSUE TITLE
DB Manager broken due to pyspatialite error 

### ISSUE THREAD

**Issue by spatialthoughts** [lutraconsulting/qgis-mac-packager#44]
DB Manager is broken for Geopackage or Spatialite databases due to a pyspatialite error (see errorlog attached) This issue also exists in  KyngChaos packages. Linux and Windows packages do not have this issue. It has been [reported](https://gis.stackexchange.com/questions/216848/pyspatialite-installation-error-on-macosx-qgis-plugin/216874#216874) by other users also.

To reproduce
- Connect to a Geopackage or Spatialit DB in QGIS.
- Open DB manager
- Browse to the DB and Open SQL Window. (spatialite crashes at this point)
- Type any sql query. (select * from <layer>) and you get an error. Python console prints the error.

The report is for package qgis_pr_final-3_4_2_20181130_083659.dmg

Thanks for the great work on the QGIS packaging. I do prefer your packages over the KyngChaos version

**Comment by spatialthoughts** [comment]
[errorlog.txt](https://github.com/lutraconsulting/qgis-mac-packager/files/2656941/errorlog.txt) attached

**Comment by saberraz** [comment]
Also confirmed in master (3.5). This is likely to be related to QGIS and sqlite/spatialite driver

**Comment by PeterPetrik** [comment]
> Also confirmed in master (3.5). This is likely to be related to QGIS and sqlite/spatialite driver

the link from stackoverflow suggests it is wrong path in python installation , probably NOT upstream bug

**Comment by spatialthoughts** [comment]
@PeterPetrik I got the version you mentioned and still see the error. Let me know if I can give you additional debug info.

<img width="1164" alt="error_log" src="https://user-images.githubusercontent.com/5227506/52688892-4c0fcf00-2f7e-11e9-86d3-273221e21254.png">
<img width="1147" alt="error" src="https://user-images.githubusercontent.com/5227506/52688893-4c0fcf00-2f7e-11e9-9267-91d552ca46f3.png">
<img width="1147" alt="version" src="https://user-images.githubusercontent.com/5227506/52688895-4c0fcf00-2f7e-11e9-9c38-dec59639aee5.png">

**Comment by PeterPetrik** [comment]
@spatialthoughts can you give it another try please?  https://www.dropbox.com/s/9mdwobzn6ru5arb/qgis_pr_final-3_4_4_20190213_064551.dmg?dl=0

**Comment by saberraz** [comment]
It works fine in https://www.dropbox.com/s/26abu37gvtotfky/qgis_pr_final-3_4_4_20190214_041422.dmg?dl=0 to run the query. But loading the query as a layer is not possible.

@spatialthoughts if you could confirm, we can close this and open another one for loading the layer.

![image](https://user-images.githubusercontent.com/2649047/52780431-06b4d580-3042-11e9-88f5-f789c36f8b71.png)

**Comment by PeterPetrik** [comment]
I am going to close this and if there is other issue, lets create new report in QGIS or here. @spatialthoughts please reopen if it does not work for you
