### ISSUE TITLE
Missing Qt driver for QGIS3.4.2 and Nightly

### ISSUE THREAD

**Issue by phborba** [lutraconsulting/qgis-mac-packager#46]
**Describe the bug**
There is a Qt component called QtSql which is only enabled if you install/compile qt with the flag --with-postgresql

If this component is not installed, some plugins that use that package will not work. This issue happens in lutra's QGIS 3.4.2 and also on nightly builds. I've provided the 2 links that I have tested.

**Additional information**

- Add link to the installed package
https://www.dropbox.com/sh/qcr9a6ry25n4x91/AAA9G6-j9ea65CYs1GdS1HVla/qgis_pr_final-3_4_2_20181212_094236.dmg?dl=0
https://www.dropbox.com/sh/cc3615b1zd7ruwz/AADwcdr0Wcsrcm_YKuEubxGba/qgis_nightly_master_20181121_022757.dmg?dl=0
- Add crash report if QGIS crashed
- State MacOS version (e.g. 10.14.1)
- The installation location of QGIS (must be /Applications/QGIS<suffix>.app)
/Applications/QGIS3.4.2.app
nightly: /Applications/QGIS.app

**Comment by phborba** [comment]
Sorry for the delay on answering you @PeterPetrik .

When I run `find /Applications/QGIS3.4.2.app -name "*QtSql*"` it outputs:
```
/Applications/QGIS3.4.2.app/Contents/MacOS/lib/QtSql.so
/Applications/QGIS3.4.2.app/Contents/PlugIns/PyQt5/QtSql.so
/Applications/QGIS3.4.2.app/Contents/Resources/python/qgis/PyQt/QtSql.py
/Applications/QGIS3.4.2.app/Contents/Resources/python/qgis/PyQt/__pycache__/QtSql.cpython-37.pyc
/Applications/QGIS3.4.2.app/Contents/Resources/python/PyQt5/QtSql.so
/Applications/QGIS3.4.2.app/Contents/Resources/python/PyQt5/QtSql.pyi
/Applications/QGIS3.4.2.app/Contents/Frameworks/QtSql.framework
/Applications/QGIS3.4.2.app/Contents/Frameworks/QtSql.framework/Versions/5/QtSql
/Applications/QGIS3.4.2.app/Contents/Frameworks/QtSql.framework/QtSql
```

Although it outputs the same as you said, but when I go to `/Applications/QGIS3.4.2.app/Contents/Frameworks/QtSql.framework/` it seems that the symlinks point to conflicting paths. One test that I usually do on QGIS python console is the one bellow:

```from qgis.PyQt.QtSql import QSqlDatabase
db = QSqlDatabase('QPSQL')
host = <your host>
port = <your port>
user = <your username> 
password = <your password>
database = 'postgres'
db.setHostName(host)
db.setPort(port)
db.setDatabaseName(database)
db.setUserName(user)
db.setPassword(password)

db.open()
if not db.isOpen():
    print('{error}'.format(error=db.lastError().text()))
```
Filling the information between < > with your own. If the driver is not loaded, it prints `Driver not loaded Driver not loaded`

When I compile my own QGIS it is just fine, because I have installed the Qt5 with the flag --with-postgresql . I have come across this once when I compiled for the first time QGIS3 without the tag --with-postgresql on Qt5 package.

**Comment by PeterPetrik** [comment]
Thanks, I will look into this after QGIS's FF at the end of this month.

**Comment by phborba** [comment]
Just a heads up, the bug still exists on 3.4.4 build

**Comment by phborba** [comment]
@PeterPetrik , I have created a pull request trying to fix this problem, could you please take a look? Thanks!

**Comment by PeterPetrik** [comment]
this is upstream problem in https://github.com/Homebrew/homebrew-core/blob/master/Formula/qt.rb
@phborba best if you raise the question upstream

i think that this may also be an ordering issue, maybe if we install postgresq BEFORE qt, qt configure may find it automatically on path?

**Comment by PeterPetrik** [comment]
asked upstream https://discourse.brew.sh/t/qt5-12-with-postgresql/4161?u=peterpetrik

**Comment by PeterPetrik** [comment]
Ah! looks like the work is already done https://github.com/OSGeo/homebrew-osgeo4mac/blob/master/Formula/qpsql.rb by @fjperini thanks! looks like we just need to add extra drivers

**Comment by PeterPetrik** [comment]
@phborba how can I test that it works , can you write me step to step guide? thanks

**Comment by PeterPetrik** [comment]
@phborba can you test with https://www.dropbox.com/s/ai69ubvt54oalty/qgis_pr_final-3_4_4_20190212_072324.dmg

**Comment by PeterPetrik** [comment]
@saberraz can you please test?

**Comment by ianhorn** [comment]
Peter,

I’m not exactly sure what you are asking me to do.  I will be glad to test, and thank you for your help.

Ian

**Comment by PeterPetrik** [comment]
you can install https://www.dropbox.com/s/ai69ubvt54oalty/qgis_pr_final-3_4_4_20190212_072324.dmg side-by-side with your official installation and see if the driver works

**Comment by ianhorn** [comment]
Ok.  Thank you.  I will try in a little bit.

On Feb 13, 2019, at 10:14 AM, Peter Petrik <notifications@github.com<mailto:notifications@github.com>> wrote:


you can install https://www.dropbox.com/s/ai69ubvt54oalty/qgis_pr_final-3_4_4_20190212_072324.dmg side-by-side with your official installation and see if the driver works

**Comment by phborba** [comment]
@PeterPetrik I'm downloading it and as soon as I test it, I'll let you know!

**Comment by phborba** [comment]
I've just tested and the problem remains =/

On the official installation the driver works.

**Comment by saberraz** [comment]
In fact the problem is worse than what's been reported. The only driver supported is `QSQLITE`

@phborba what do you get if you open python console and type the followings:
```
from PyQt5.QtSql import QSqlDatabase
QSqlDatabase.drivers()
```

**Comment by phborba** [comment]
Only QSQLITE :/

**Comment by PeterPetrik** [comment]
got it!

```
from PyQt5.QtSql import QSqlDatabase
QSqlDatabase.drivers()
['QSQLITE', 'QMYSQL', 'QMYSQL3', 'QODBC', 'QODBC3', 'QPSQL', 'QPSQL7']
```

package soon!

**Comment by PeterPetrik** [comment]
@phborba @saberraz  can you test with https://www.dropbox.com/s/mx8njnkmbtcaq6x/qgis_pr_final-3_4_4_20190214_075146.dmg?dl=0

**Comment by saberraz** [comment]
Nice one @PeterPetrik 
The last build addressed the issue.

**Comment by phborba** [comment]
Yay! It worked! Thanks a lot @PeterPetrik !!!
