### ISSUE TITLE
Using virtualenv for qgis

### ISSUE THREAD

**Issue by RemiDesgrange** [lutraconsulting/qgis-mac-packager#47]
Instead of installing package globaly, why not using a virtualenv, sorted in `/Applications/Qgis.app/Content/Resources` or other. I don't know well mac os packaging. But still could help rebuild qgis python module when broken without blowing up the whole system python.

If you can give me hint, I can try to put up a PR for this.

**Comment by joaoponceleao** [comment]
A safer possibility might be to use pyenv (https://github.com/pyenv/pyenv). It's also on homebrew and that would allow Qgis to: 1) Use a specific python version. 2) Not have to worry about issues which sometimes crop up when using virtualenvs.

**Comment by PeterPetrik** [comment]
Not sure if I understand the benefit of virtualenv/pyenv since this package has fully-bundled own python3 installation inside the bundle. So it does not interact with system/global python3 any way

**Comment by joaoponceleao** [comment]
In that case this is a non-issue. I noticed in issue #41 problems with installing python packages (binaries going in /usr/local/bin for example) so I wrongly *assumed* it was interacting with a global python. Sorry about that.

**Comment by PeterPetrik** [comment]
no problem at all, thank you for discussion. closing this

**Comment by RemiDesgrange** [comment]
OK sorry, I though you were using python from the system. Sorry for the noise.
