### ISSUE TITLE
Shared QGIS3 user preferences between various packages

### ISSUE THREAD

**Issue by joaoponceleao** [lutraconsulting/qgis-mac-packager#48]
**All Qgis 3 packages (including kyngchaos) are using same preferences**

At the moment Qgis gets its preferences from the qgis3 preferences file somewhere in the mac library. These are shared amongst all Qgis 3 installations. This creates two issues:
1. One of the ideas behind this project is to have multiple minor version installations. They should therefore have multiple minor version preference files.
2. The traditional Qgis install on Mac is still the Kyngchaos install. In his version, you have to prepend the paths for the kyngchaos Geos and GDAL on the Qgis 3 preferences pane. This then gets shared with this version of Qgis meaning that issues may crop up with people not realising that the kyngchaos frameworks are overriding the ones that came with this package.

**Additional information**

- MacOS version (e.g. 10.13.6)
- Location /Applications/QGIS3.4.2.app

**Comment by PeterPetrik** [comment]
traditionally you want to share preferences between various qgis3 installations (so you do not need to reinstall things or reset your preferences after each update). But it would be maybe good idea to have different preferences folder for ALL qgis3 packages from qgis-mac-packager builds.

**Comment by joaoponceleao** [comment]
Yes. I can certainly se the benefit of sharing preferences for all qgis3 coming from the same source. The issue here is more to do with the fact that kyngchaos needs Path changes within the qgis3 preferences file. Ideally he should not need it (did not use to be the case for qgis2).

**Comment by PeterPetrik** [comment]
The repository is no longer used, because QGIS Mac packaging system is moved under OSGEO/QGIS repository https://github.com/qgis/QGIS-Mac-Packager. Please reopen the issue in the new repository if it is still an issue
