### ISSUE TITLE
Readability issues dark moge

### ISSUE THREAD

**Issue by leonmvd** [lutraconsulting/qgis-mac-packager#54]
On several places the readability could be improved. Mostly text labels.

In this case Macintosh Style:

![screen shot 2019-01-22 at 10 46 58](https://user-images.githubusercontent.com/9214202/51526748-51707280-1e33-11e9-83f8-a877696b057c.png)
![screen shot 2019-01-22 at 10 46 38](https://user-images.githubusercontent.com/9214202/51526750-52a19f80-1e33-11e9-94d8-d26e6a4a538d.png)

or Fusion

![screen shot 2019-01-22 at 10 50 10](https://user-images.githubusercontent.com/9214202/51526855-8da3d300-1e33-11e9-8e48-5066467915bb.png)

**Comment by PeterPetrik** [comment]
Hi, thank you for reporting Mac-related bugs.  

there is already some work done (e.g. https://github.com/qgis/QGIS/pull/8738). Can you please create this ticket in https://issues.qgis.org/projects/qgis/issues, since this is not related to packaging, but QGIS code?

thanks!

**Comment by wonder-sk** [comment]
Actually recently there has been a whole stream of pull requests in QGIS for both 3.4 and 3.6 fixing lots of issues in dark mode so these problems should go away in packages as well.

**Comment by leonmvd** [comment]
https://issues.qgis.org/issues/21072
