### ISSUE TITLE
Better distribution of the binary packages

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mac-packager#56]
Sometimes it is difficult to find the latest package in the dropbox folder:
- It would be good to have older versions in a folder and only the latest outside.
- To be consistent with Windows builds, we can call the packages with the build: e.g. 3.4.5-1, 3.4.5-2, with dates, it is too long!

**Comment by PeterPetrik** [comment]
as a workaround dropbox allows to sort files by modified column @timlinux

**Comment by saberraz** [comment]
Shall we have only the latest version available and move others to a folder. If it can be done through script, great. Otherwise, I am happy to do it manually.

**Comment by PeterPetrik** [comment]
if you move files around it will break links around internet pointing to origin location

I think copy latest (tested) files for point release and LTR to folder "official" or "latest" is better option.

this could be scripted but require few hours of work with dropbox API. if we want to have only tested version there, better to do it manually.

**Comment by PeterPetrik** [comment]
I think that the binary packages we produce now should be tested and then distribute by other canals (as official/unofficial QGIS packages)
