### ISSUE TITLE
Dark theme legend illegible

### ISSUE THREAD

**Issue by timlinux** [lutraconsulting/qgis-mac-packager#57]
**Describe the bug**
Using 3.4.4 in dark mode

<img width="381" alt="screenshot 2019-02-11 at 00 08 38" src="https://user-images.githubusercontent.com/178003/52540365-5c168b80-2d91-11e9-991d-f38dbe122945.png">

**Comment by nirvn** [comment]
Backporting this commit, https://github.com/qgis/QGIS/commit/9200f538e9104927c6f77ca1e9514f90e49a4fbc , will fix this. It slipped through.

**Comment by PeterPetrik** [comment]
thanks @nirvn

**Comment by PeterPetrik** [comment]
fixed upstream

**Comment by nirvn** [comment]
https://github.com/qgis/QGIS/commit/4be150c58bfd063570cd559e59a1c59d0c82f155
