### ISSUE TITLE
Include proj-datumgrid package

### ISSUE THREAD

**Issue by nyalldawson** [lutraconsulting/qgis-mac-packager#58]
The proj-datumgrid package includes grid transform files which are required for accurate coordinate transformation in certain regions. Could this be included in the package so that these grid shift files are available "out of the box"?

https://github.com/OSGeo/proj-datumgrid

**Comment by PeterPetrik** [comment]
so I just need to unpack the repository to proj data folder as it is? or just subfolders (europe, oceania, ...)?

also how do I check in QGIS that it is installed and working correctly?

**Comment by nyalldawson** [comment]
Initially yes -- the second part relies on something like https://github.com/qgis/QGIS/pull/9160

**Comment by PeterPetrik** [comment]
hmm, I am thinking if it would not be better to somehow improve projection selection dialog in qgis and interactively be able to download required grids from the repo when needed similarly to plugin manager or something like that. Only requirement would be that proj package would need to be able to dynamically load multiple folders (e.g. sysmte proj folder, user profile folder) or something similar.

**Comment by PeterPetrik** [comment]
<img width="509" alt="screenshot 2019-02-12 at 16 59 25" src="https://user-images.githubusercontent.com/804608/52648908-94c87900-2ee7-11e9-9cd0-3369737dd5ea.png">

it looks like now it is around 250MB extra. Current size of the package is 360 MB. @nyalldawson do you know if it will grow rapidly or 250MB is pretty much final size of it?

**Comment by nyalldawson** [comment]
> do you know if it will grow rapidly or 250MB is pretty much final size of it?

@PeterPetrik I honestly can't say -- there's an open PR adding a Belgium grid (+5.5 mb) which is likely to be merged soon.

There's also https://github.com/OSGeo/proj-datumgrid/issues/22 -- but discussion there seems to have stalled due to licensing issues. And https://github.com/OSGeo/proj-datumgrid/issues/41 - but that's not going to happen until 2020, and no indication of the grid size.

**Comment by PeterPetrik** [comment]
@nyalldawson so to mimic OSGeo4W behaviour, the task now is to add `oceania` folder to the bundle to the location of PROJ data files? 

also how can I test that it works (please simple step by step) thanks!

**Comment by nyalldawson** [comment]
> also how can I test that it works (please simple step by step) thanks!

Heh - that's not so simple :P 

You'd need
1. latest master of 3.7/3.6/3.4 (with the recent GDA2020 commit)
2. The two layers files from http://lctest.land.vic.gov.au/SpatialDatamart4/gda2020/sample_shape_files.zip
3. From qgis options, CRS settings, ensure "ask for datum transformation if several are available" is checked
4.  Drag and drop both layers simultaneously to a new project
5. you should get the datum transform dialog prompt , with a choice of two grids. Choose the variant with "local distortion"
6. the points should be exactly co-incident

**Comment by nyalldawson** [comment]
Hi @PeterPetrik ! Is there anything I can do to assist with this? I can get access temporarily to a mac for testing, if you'd like me to do that part?

**Comment by PeterPetrik** [comment]
@nyalldawson homebrew installs by default this https://github.com/Homebrew/homebrew-core/blob/master/Formula/proj.rb#L27 . Do you know if it is the same stuff as in the https://github.com/OSGeo/proj-datumgrid/releases or completely different (we need both, or only that from homebrew, or?)

**Comment by nyalldawson** [comment]
@PeterPetrik that one is just a handful of random grids -- the useful ones are the separate oceania/europe/north-america packages (and to a lesser extent world, although that one only contains vertical grids and is of limited (no?) current interest to QGIS)

**Comment by PeterPetrik** [comment]
@nyalldawson can you try https://www.dropbox.com/s/f8cyxkcdko1h36q/qgis_nightly_master_20190321_152115.dmg?dl=0

those files should be under QGIS.app/Content/Resources/proj/proj/ or something like that
