### ISSUE TITLE
Support for ECW format

### ISSUE THREAD

**Issue by PeterPetrik** [lutraconsulting/qgis-mac-packager#59]
https://www.hexagongeospatial.com/products/power-portfolio/compression-products/erdas-ecw-jp2-sdk

**Comment by saberraz** [comment]
https://trac.osgeo.org/gdal/wiki/ECW

**Comment by saberraz** [comment]
Example data:
https://www.harita.gov.tr/english/images/urun/I33A1_Ecw.zip

**Comment by PeterPetrik** [comment]
https://github.com/OSGeo/homebrew-osgeo4mac/blob/master/Formula/gdal2-ecwjp2.rb

https://github.com/OSGeo/homebrew-osgeo4mac/blob/master/Formula/ecwjp2-sdk.rb

**Comment by saberraz** [comment]
[license_ecw.txt](https://github.com/lutraconsulting/qgis-mac-packager/files/2880663/license_ecw.txt)

**Comment by PeterPetrik** [comment]
@saberraz can you please test with https://www.dropbox.com/s/jnty3t88jbs7u0f/qgis_pr_final-3_4_4_20190220_045748.dmg?dl=0
