### ISSUE TITLE
QGIS can't be installed: unsecured source (Dropbox)

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mac-packager#61]
![image](https://user-images.githubusercontent.com/2649047/52696073-00e9c200-2f66-11e9-9e8e-b191b0fa603f.png)

**Comment by PeterPetrik** [comment]
@saberraz can you try 

```
codesign --verbose --deep-verify /Applications/QGIS ....
codesign -d -vvvv ....
```

on both dmg and extracted application and send me output?

**Comment by ianhorn** [comment]
Ians-iMac:Applications ianhorn$ codesign --verbose --deep-verify /Applications/QGIS3.app
/Applications/QGIS3.app: code object is not signed at all
In architecture: x86_64
Ians-iMac:Applications ianhorn$ codesign --verbose --deep-verify /Applications/QGIS3.4.4.app

/Applications/QGIS3.4.4.app: code object is not signed at all
In subcomponent: /Applications/QGIS3.4.4.app/Contents/Frameworks/QtWebKit.framework
Ians-iMac:Applications ianhorn$
Ians-iMac:Applications ianhorn$ codesign -d -vvvv /Applications/QGIS3.app
/Applications/QGIS3.app: code object is not signed at all
Ians-iMac:Applications ianhorn$ codesign -d -vvvv /Applications/QGIS3.4.4.app
Executable=/Applications/QGIS3.4.4.app/Contents/MacOS/QGIS
Identifier=org.qgis.qgis344
Format=app bundle with Mach-O thin (x86_64)
CodeDirectory v=20200 size=39408 flags=0x0(none) hashes=1226+3 location=embedded
VersionPlatform=1
VersionMin=658176
VersionSDK=658944
Hash type=sha256 size=32
CandidateCDHash sha1=43fb60d59e21a5eb7d884c521fa8937a1f22375c
CandidateCDHash sha256=c26c588d82845302c169981e66c61a16567391bc
Hash choices=sha1,sha256
Page size=4096
CDHash=c26c588d82845302c169981e66c61a16567391bc
Signature size=9029
Authority=Developer ID Application: LUTRA CONSULTING LIMITED (79QMH2QRAH)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=Feb 13, 2019 at 7:00:33 AM
Info.plist entries=19
TeamIdentifier=79QMH2QRAH
Sealed Resources version=2 rules=13 files=24846
Internal requirements count=1 size=176
Ians-iMac:Applications ianhorn$

On Feb 13, 2019, at 11:18 AM, Peter Petrik <notifications@github.com<mailto:notifications@github.com>> wrote:


@saberraz<https://github.com/saberraz> can you try

codesign --verbose --deep-verify /Applications/QGIS ....
codesign -d -vvvv ....


on both dmg and extracted application and send me output?

**Comment by ianhorn** [comment]
I went back and reinstalled the version you sent me:

Ians-iMac:Applications ianhorn$ codesign --verbose --deep-verify /Applications/QGIS3.4.4.app
/Applications/QGIS3.4.4.app: a sealed resource is missing or invalid
In subcomponent: /Applications/QGIS3.4.4.app/Contents/Frameworks/Python.framework
Ians-iMac:Applications ianhorn$ code -d -vvvv /Applications/QGIS3.4.4.app
-bash: code: command not found
Ians-iMac:Applications ianhorn$ codesign -d -vvvv /Applications/QGIS3.4.4.app
Executable=/Applications/QGIS3.4.4.app/Contents/MacOS/QGIS
Identifier=org.qgis.qgis344
Format=app bundle with Mach-O thin (x86_64)
CodeDirectory v=20200 size=39408 flags=0x0(none) hashes=1226+3 location=embedded
VersionPlatform=1
VersionMin=658176
VersionSDK=658944
Hash type=sha256 size=32
CandidateCDHash sha1=8255ea96c61b22d38851e5c040ea61c6e1489a1a
CandidateCDHash sha256=6ac55ca0c4176d65f5416a1a4fd50a03c82563ec
Hash choices=sha1,sha256
Page size=4096
CDHash=6ac55ca0c4176d65f5416a1a4fd50a03c82563ec
Signature size=9029
Authority=Developer ID Application: LUTRA CONSULTING LIMITED (79QMH2QRAH)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=Feb 12, 2019 at 8:36:33 AM
Info.plist entries=19
TeamIdentifier=79QMH2QRAH
Sealed Resources version=2 rules=13 files=24845
Internal requirements count=1 size=176
Ians-iMac:Applications ianhorn$

On Feb 13, 2019, at 11:18 AM, Peter Petrik <notifications@github.com<mailto:notifications@github.com>> wrote:


@saberraz<https://github.com/saberraz> can you try

codesign --verbose --deep-verify /Applications/QGIS ....
codesign -d -vvvv ....


on both dmg and extracted application and send me output?

**Comment by ianhorn** [comment]
After installing the version you gave me, I still am getting the same errors when trying to creat an MSSQL connection.  I tried the gdalinfo command again and also go same results.

On Feb 13, 2019, at 12:21 PM, Ian Horn <ian.horn@ky.gov<mailto:ian.horn@ky.gov>> wrote:

I went back and reinstalled the version you sent me:

Ians-iMac:Applications ianhorn$ codesign --verbose --deep-verify /Applications/QGIS3.4.4.app
/Applications/QGIS3.4.4.app: a sealed resource is missing or invalid
In subcomponent: /Applications/QGIS3.4.4.app/Contents/Frameworks/Python.framework
Ians-iMac:Applications ianhorn$ code -d -vvvv /Applications/QGIS3.4.4.app
-bash: code: command not found
Ians-iMac:Applications ianhorn$ codesign -d -vvvv /Applications/QGIS3.4.4.app
Executable=/Applications/QGIS3.4.4.app/Contents/MacOS/QGIS
Identifier=org.qgis.qgis344
Format=app bundle with Mach-O thin (x86_64)
CodeDirectory v=20200 size=39408 flags=0x0(none) hashes=1226+3 location=embedded
VersionPlatform=1
VersionMin=658176
VersionSDK=658944
Hash type=sha256 size=32
CandidateCDHash sha1=8255ea96c61b22d38851e5c040ea61c6e1489a1a
CandidateCDHash sha256=6ac55ca0c4176d65f5416a1a4fd50a03c82563ec
Hash choices=sha1,sha256
Page size=4096
CDHash=6ac55ca0c4176d65f5416a1a4fd50a03c82563ec
Signature size=9029
Authority=Developer ID Application: LUTRA CONSULTING LIMITED (79QMH2QRAH)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=Feb 12, 2019 at 8:36:33 AM
Info.plist entries=19
TeamIdentifier=79QMH2QRAH
Sealed Resources version=2 rules=13 files=24845
Internal requirements count=1 size=176
Ians-iMac:Applications ianhorn$

On Feb 13, 2019, at 11:18 AM, Peter Petrik <notifications@github.com<mailto:notifications@github.com>> wrote:


@saberraz<https://github.com/saberraz> can you try

codesign --verbose --deep-verify /Applications/QGIS ....
codesign -d -vvvv ....


on both dmg and extracted application and send me output?

**Comment by saberraz** [comment]
Same error as above:
`/Applications/QGIS3.4.4.app: code object is not signed at all In subcomponent: /Applications/QGIS3.4.4.app/Contents/Frameworks/QtWebKit.framework
`
And on the dmg file:
![image](https://user-images.githubusercontent.com/2649047/52770430-f6453080-302a-11e9-8c77-7dd97ffea003.png)

**Comment by saberraz** [comment]
`codesign -d -vvvv qgis....dmg:`
![image](https://user-images.githubusercontent.com/2649047/52770485-25f43880-302b-11e9-8393-9892110d8868.png)

**Comment by saberraz** [comment]
`codesign -d -vvvv /Application/QGIS.3.4.4/`
![image](https://user-images.githubusercontent.com/2649047/52771074-d0b92680-302c-11e9-8ebc-78ce7d52b6e8.png)

**Comment by saberraz** [comment]
`codesign --verbose --deep-verify /Applications/QGIS ....`
**`/Applications/QGIS3.4.4.app: code object is not signed at all In subcomponent: /Applications/QGIS3.4.4.app/Contents/Frameworks/QtWebKit.framework`**

**Comment by PeterPetrik** [comment]
This is sideeffect of #62, since QtWebKit binary is not present in the bundle at all. Can you please retest with
https://www.dropbox.com/s/26abu37gvtotfky/qgis_pr_final-3_4_4_20190214_041422.dmg?dl=0
