### ISSUE TITLE
Crash when moving dock widgets

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mac-packager#67]
Getting a crash when trying to move dock widgets around (in current LTR build)

**Comment by saberraz** [comment]
Could you try with a fresh profile?

**Comment by saberraz** [comment]
Ok, I can confirm the issue. To reproduce:

1- Add a layer
2- Move a panel (e.g. Processing toolbox) and try to dock it somewhere else
3- Complete crash

**Comment by PeterPetrik** [comment]
I am not able to reproduce @saberraz do you have a crash report ?

**Comment by saberraz** [comment]
It looks intermittent and I can't reproduce it consistently.

**Comment by Spartacus1** [comment]
It's stable in my case. No issues. 
The latest qgis_nightly_master_20190220_121012.dmg is very good!! Despite the Grass known issues, everything is working with very stability and the interface seems to be a lot more polished. The latest geometry validation tools in real time are incredibly good. You have to activate them from the layer properties. I've been testing for quite a while with a complex project with no issues. 
Be wise and use the white interface, not the dark mode. In dark mode the interface is inconsistent. It's hard to see, for instance, which options are activated in the snapping options toolbar. In white mode it very easy to see. This kind of things clearly need to be tweaked in dark mode.

**Comment by PeterPetrik** [comment]
The repository is no longer used, because QGIS Mac packaging system is moved under OSGEO/QGIS repository https://github.com/qgis/QGIS-Mac-Packager. Please reopen the issue in the new repository if it is still an issue
