### ISSUE TITLE
Forms always show 'collapsed'

### ISSUE THREAD

**Issue by timlinux** [lutraconsulting/qgis-mac-packager#68]
Whenever I open a form (using your QGIS 3.4 package from Feb  19) the form shows 'collapsed' and needs to be manually sized. Which really kills productivity.

![forms](https://user-images.githubusercontent.com/178003/53141784-eab5b480-35aa-11e9-86e9-27a7a793a568.gif)

**Comment by PeterPetrik** [comment]
@timlinux do you have them collapsed even if next time you open the same form?

**Comment by saberraz** [comment]
I am using https://www.dropbox.com/sh/qcr9a6ry25n4x91/AAB-JZZvq5mml3Y90yBrkvPFa/qgis_pr_final-3_4_4_20190220_045748.dmg with a clean user profile and can't reproduce the issue:
![forms](https://user-images.githubusercontent.com/2649047/53151307-cbb72280-35aa-11e9-9578-f53f7f8c9cf7.gif)

**Comment by Spartacus1** [comment]
This happens in my case too. Dialogues appear collapsed just as timlinux showed.

**Comment by dd-a** [comment]
Same for me.  

Didier

**Comment by iungurianu** [comment]
Hi. It seems that the error appears only on the default user profile (form and grass error - see attached). If you set a new profile everything is ok, grass error disappear and form don't collapsed
![screenshot 2019-03-02 at 11 55 46](https://user-images.githubusercontent.com/15980175/53681360-3249e800-3cf1-11e9-9285-3ae7d120f4ef.png)
.

**Comment by PeterPetrik** [comment]
Closing, @timlinux please reopen if you can replicate it with clean user profile
