### ISSUE TITLE
QGIS NB 3.7 Python error

### ISSUE THREAD

**Issue by Spartacus1** [lutraconsulting/qgis-mac-packager#73]
While starting up the latest NB, the following error occurs:

"Couldn't load PyQGIS.
Python support will be disabled."

Then all the Pithon related features are disabled (plugins, processing, etc, etc.)

Cheers

**Comment by PeterPetrik** [comment]
Hi, 

which MacOS version?
which installer link? 
Any particular message in QGIS log, console, etc?

P.

**Comment by Spartacus1** [comment]
Hi Peter

The MacOS version is 10.4.4 (beta).
The "qgis_nightly_master_20190309_121007" version works just fine. 
However something change from that version to qgis_nightly_master_20190310_121011 that made it unusable. The only thing that appeared was that error. Today I've uninstalled this version, installed the older one, erased it, installed again the  qgis_nightly_master_20190310_121011 version and the error is gone. Did you change anything? For now nothing to worry about. 
Cheers

**Comment by PeterPetrik** [comment]
you mean 10.14.4 right? 
we did not changed anything during weekend, so I assume it may be something in the qgis code?

**Comment by Spartacus1** [comment]
Yup, 10.14.4 (the latest Beta - I'm in Apple's Beta program). 
QGIS 3.7 it's working fine now. Still don't know the origin of that glitch but it almost corrected by itself. The only thing that happened is that all the toolbars got activated. I had to deactivate some by hand because, otherwise, QGIS cannot be fitted in the screen area.

**Comment by PeterPetrik** [comment]
lets reopen when it comes again
