### ISSUE TITLE
Missing QtWebKit and QtWebKitWidgets in PyQt

### ISSUE THREAD

**Issue by Spartacus1** [lutraconsulting/qgis-mac-packager#75]
Latest "qgis_nightly_master_20190321_152115" built has lots of issues, mainly related with PyQt5.

Examples of headers from errors:

Couldn't load plugin 'DataPlotly' due to an error when calling its classFactory() method  
ModuleNotFoundError: No module named 'PyQt5.QtWebKit' 

Couldn't load plugin 'qgis2web' due to an error when calling its classFactory() method  
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets' 

Couldn't load plugin 'Qgis2threejs' due to an error when calling its classFactory() method  
ModuleNotFoundError: No module named 'PyQt5.QtWebKit' 

Couldn't load plugin 'parcel_plugin' due to an error when calling its classFactory() method  
ImportError: cannot import name 'QtWebKitWidgets' from 'PyQt5' 

(/Applications/QGIS3.7.app/Contents/MacOS/../Resources/python/PyQt5/__init__.py) 
Couldn't load plugin 'openlayers_plugin' due to an error when calling its classFactory() method  

ImportError: cannot import name 'QtWebKitWidgets' from 'PyQt5' (/Applications/QGIS3.7.app/Contents/MacOS/../Resources/python/PyQt5/__init__.py) 

![Uploading Screen Shot 2019-03-21 at 21.55.33.png…]()

etc.

Cheers

**Comment by PeterPetrik** [comment]
Hmm, are all those error about QtWebKit and QtWebKitWidgets? They are both deprecated/removed in laterst Qt/PyQt versions. Also all the errors comes from the installed plugins and not from core plugins/QGIS.

see https://stackoverflow.com/questions/37876987/cannot-import-qtwebkitwidgets-in-pyqt5

Can you please confirm that all those errors are from QtWebKitWidgets and QtWebKit? If yes, it is better to raise issues in the issue trackers of those plugins.

**Comment by PeterPetrik** [comment]
ah, found out that dep was again renamed in homebrew https://github.com/OSGeo/homebrew-osgeo4mac/blob/master/Formula/osgeo-pyqt-webkit.rb. let me try with that one

**Comment by Spartacus1** [comment]
Great Peter. Once you have a working version let me know. The previous one was working quite well.

**Comment by Spartacus1** [comment]
The latest one available, compiled today, still shows the same issue. It's very unstable. It crashes a lot, even while opening projects.

**Comment by PeterPetrik** [comment]
👎  :(  everything in homebrew-osgeo is renamed again so I need to spend some time to make it work again

**Comment by Spartacus1** [comment]
These changes are annoying and, at least some of them, happen without any obvious need. Good luck and be patient ;-) At least your stable version is working quite well.

**Comment by fjperini** [comment]
Sorry for the inconvenience. But know understand that we decided to rename formulas to make other things simpler.
The process took time due to the restrictions in CI and the delay of Homebrew Core in updating many of the dependencies, for example Qt and PROJ (a few hours ago). This leads to rebuild all the bottles.
For this reason and another is that we were working on optimizing the tap for the future.

We want to have more control of the updates and supports.

p/d: I will be rebuilding everything for PROJ 6.

**Comment by PeterPetrik** [comment]
@fjperini no problem, understand... would it be possible to ping me on peter.petrik@lutraconsulting.co.uk when something like this happens with lets say for how long it will be unavailable so I am aware that I should not try to update repos at that time? Thanks for your work.

**Comment by fjperini** [comment]
@PeterPetrik I'm sorry if the warning did not arrive. It's something that we were discussing in the repo and we decided to do it.
As for the formulas that qgis-mac-packager requires, they are all ready, but ... given that there are updates that require us to rebuild several bottles, I recommend that you wait until you finish with that.

I hope to have everything ready for today!

**Comment by PeterPetrik** [comment]
so some of the bottles are not yet ready? In that case please send me mail when everything is OK?

**Comment by fjperini** [comment]
recently updated proj, that makes that we have to reconstruct all the dependencies.
we will use our own version of proj, to avoid this in the future.
I'll write you when everything is ready.

**Comment by Spartacus1** [comment]
Thank you so much fjperini!

**Comment by PeterPetrik** [comment]
proj6? Are all libraries compatible with it?

**Comment by fjperini** [comment]
It seems that yes, at least they have managed to build all those that depend on it.
https://github.com/Homebrew/homebrew-core/pull/38215

**Comment by fjperini** [comment]
there are dependencies that are common to all, and some of their libraries are called with libname.X.dylib .... which makes us need to rebuild all those that depend on them.
To have more control of when to update and not do double work, we will use our versions.
With this we save time and work, which is a lot if we do not do everything in a synchronized way.

**Comment by PeterPetrik** [comment]
https://github.com/OSGeo/proj.4/wiki/proj.h-adoption-status

not sure if we are ready for proj6

**Comment by PeterPetrik** [comment]
@fjperini any idea when the build will be ready?

**Comment by fjperini** [comment]
I'm on it!
Also a new gdal version came out, so updating everything that depends on it.

**Comment by fjperini** [comment]
There are problems in Bintray, being an open source account has its limitations.

I will contact the people of Bintray to find a solution, or we will have to pay to have an improved service.

**Comment by PeterPetrik** [comment]
@fjperini can you write me your email on peter.petrik@lutraconsulting.co.uk please?

**Comment by PeterPetrik** [comment]
https://github.com/lutraconsulting/qgis-mac-packager/issues/82

**Comment by PeterPetrik** [comment]
@Spartacus1 can you try this one https://www.dropbox.com/s/q4i7jc1vqfospqu/qgis_nightly_master_20190402_081155.dmg?dl=0 ?

**Comment by Spartacus1** [comment]
Hi Peter. Seems to be working great. There are two plug-ins that get deactivated but it's clearly a problem linked to those plug-ins. One of them is Profile Tool which is very handy. Considering the mais App, so far so good. Most major problems seem to be gone. I have not tested in detail yet. Let's see how most processing modules perform. Cheers
