### ISSUE TITLE
Question about nomenclature

### ISSUE THREAD

**Issue by juanfcocontreras** [lutraconsulting/qgis-mac-packager#79]
I'm so sorry for the beginner question, but what does QGIS "PR" stand for? I tried to find it, but I can't find any reference. I noticed that LTR stands for Long-Term Release, but PR stands for Production,...?

Thanks in advance!

**Comment by PeterPetrik** [comment]
PR is for Point Release, see. https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule

good question!
