### ISSUE TITLE
No latest builds

### ISSUE THREAD

**Issue by palmerj** [lutraconsulting/qgis-mac-packager#84]
The last nightly builds were 10 days ago. Also the latest 3.6.X point releases have not been built.

**Comment by saberraz** [comment]
@palmerj we are in process of moving the infrastructure to QGIS. They should all appear soon here:
https://qgis.org/downloads/macos/

**Comment by palmerj** [comment]
Thanks. We can close this then.

**Comment by PeterPetrik** [comment]
this is connected with transition to proj6: commit https://github.com/qgis/QGIS/commit/018f3bc19bbffb3958aba8e3f13208b9589d78da . should be fixed next week
