### ISSUE TITLE
update to qt 5.12

### ISSUE THREAD

**Issue by PeterPetrik** [lutraconsulting/qgis-mac-packager#9]
http://blog.qt.io/blog/2018/11/08/qt-macos-10-14-mojave/

**Comment by PeterPetrik** [comment]
depends on when homebrew-core updates qt to 5.12

**Comment by PeterPetrik** [comment]
https://github.com/Homebrew/homebrew-core/blob/master/Formula/qt.rb

**Comment by Malauch** [comment]
When it is going to be updated to QT 5.12? I'm just curious because I hope it would solve problem with QGIS very slow performance on high screen displays with QT 5.10 and 5.11.

**Comment by saberraz** [comment]
there is a bigger blocker atm with 5.10 and 5.11: #22 
That aside, homebrew core appears to have added the support for qt 5.12

**Comment by PeterPetrik** [comment]
I hope I can do it this week.

**Comment by PeterPetrik** [comment]
> there is a bigger blocker atm with 5.10 and 5.11: #22
that one is blocker for MacOS 10.11 and 10.12, not related to Qt at all

**Comment by saberraz** [comment]
my bad!

**Comment by PeterPetrik** [comment]
@saberraz @PeterPetrik updated PR release https://www.dropbox.com/s/i14wnupd20ohloh/qgis_pr_final-3_4_2_20181212_094236.dmg?dl=0
can you please check if it works ok with Qt5.12?

nightly release will come in ~5 hours as usually.

**Comment by saberraz** [comment]
Checked master and it is indeed with Qt 5.12

**Comment by saberraz** [comment]
QGIS 3.4.2 is now with Qt 5.12. Thanks @PeterPetrik
